# Generated by Django 5.2 on 2025-05-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_scheduleslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.CharField(blank=True, max_length=255, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='languages',
            field=models.CharField(blank=True, max_length=255, verbose_name='Языки преподавания'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='video_intro',
            field=models.URLField(blank=True, null=True),
        ),
    ]
