# Generated by Django 5.2 on 2025-05-14 09:04

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='country_of_birth',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Страна рождения'),
        ),
    ]
