# Generated by Django 5.1.7 on 2025-04-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('teacher', '0003_scheduleslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='schedule_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.scheduleslot'),
        ),
    ]
